[2017-10-25 17:11:29,688 - ERROR : validate.py:93 - check_count() ] ERROR: Goals goalid (strings_td_myfs) has invalid resulttag (xxxxngs_td_myfs)
